#ifndef _GROEI_DEFINITIONS_H_
#define _GROEI_DEFINITIONS_H_
#include <stdint.h>

#define GROEI_ERROR_INIT_CODE 1
#define GROEI_ERROR_WINDOW_CODE 2
#define GROEI_ERROR_RENDERER_CODE 3
#define GROEI_ERROR_DEBUG_MESSENGER_CODE 4
#define GROEI_ERROR_SURFACE_CODE 5
#define GROEI_ERROR_PHYSICAL_DEVICE_CODE 6
#define GROEI_ERROR_LOGICAL_DEVICE_CODE 7
#define GROEI_ERROR_SWAP_CHAIN_CODE 8
#define GROEI_ERROR_IMAGE_VIEWS_CODE 9
#define GROEI_ERROR_RENDER_PASS_CODE 10
#define GROEI_ERROR_SHADER_CODE 11
#define GROEI_ERROR_GRAPHICS_PIPELINE_LAYOUT_CODE 12
#define GROEI_ERROR_GRAPHICS_PIPELINE_CODE 13
#define GROEI_ERROR_CREATE_SHADER_MODULE_CODE 14
#define GROEI_ERROR_FRAME_BUFFER_CODE 15
#define GROEI_ERROR_COMMAND_POOL_CODE 16
#define GROEI_ERROR_VERTEX_BUFFER_CODE 16
#define GROEI_ERROR_COMMAND_BUFFERS_CODE 17
#define GROEI_ERROR_COMMAND_BUFFER_RECORD_CODE 18
#define GROEI_ERROR_SYNCHRONIZATION_CODE 19

#define GROEI_ERROR_RENDERER_LAYERS 20

#define GROEI_ERROR_VALIDATION_LAYERS 30

#define GROEI_ERROR_LOADING_FILE_CODE 50

typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;

#endif
